### PR TITLE
Support permanent redirects

### PR DESCRIPTION
**Pull request by majelbstoat**
Hello @nicks, @dpup, 

Please review the following commits I made in branch 'jamie-permanent-redirect-support'.

901de2ae4e3de9aa14728070b708096abc696a0f (2015-03-13 13:50:13 -0700)
Support permanent redirects

R=@nicks
R=@dpup

### CODE REVIEW

**Comment by nicks** [comment]
the boolean argument seems...surprising. should it just be a separate method?

**Comment by majelbstoat** [comment]
I mean, I could. Just seemed like a different flavour of redirect. Strong preference?

**Comment by nicks** [comment]
ya, it seems pretty likely that this will bite us if we do it this way, due to the
.then(res.redirect.bind(res, location))
problem

**Comment by majelbstoat** [comment]
oh, good point. yup, will change.

**Comment by majelbstoat** [comment]
Changes made, ready for a second pass.

**Comment by nicks** [comment]
lgtm

**Pull request merged**
